-- Tạo bảng LoaiVT
CREATE TABLE LoaiVT (
    MaLVT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenLVT VARCHAR2(100) NOT NULL
);

-- Tạo bảng NhaCungCap
CREATE TABLE NhaCungCap (
    MaNCC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenNCC VARCHAR2(100) NOT NULL
);

-- Tạo bảng KhachHang
CREATE TABLE KhachHang (
    MaKH NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenKH VARCHAR2(100) NOT NULL,
    SDT VARCHAR2(15)
);

-- Tạo bảng NhanVien
CREATE TABLE NhanVien (
    MaNV NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenNV VARCHAR2(100) NOT NULL,
    NgayVaoLam DATE,
    Luong NUMBER,
    ChucVu VARCHAR2(50) NOT NULL,
    TenDangNhap VARCHAR2(50) NOT NULL,
    MatKhau VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) NOT NULL,
    CONSTRAINT CK_ChucVu CHECK (ChucVu IN ('KeToan', 'NhapXuat', 'NghiemThu','Admin'))
);

-- Tạo bảng NhaVanChuyen
CREATE TABLE NhaVanChuyen (
    MaNVC NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenNVC VARCHAR2(100) NOT NULL,
    SDT_DaiDien VARCHAR2(15)
);

-- Tạo bảng VatTu
CREATE TABLE VatTu (
    MaVT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenVT VARCHAR2(100) NOT NULL,
    MaLVT NUMBER NOT NULL,
    DonGiaNhap NUMBER NOT NULL,
    DonGiaXuat NUMBER,
    SoLuong NUMBER DEFAULT 0,
    TrangThai NUMBER CONSTRAINT CK_TrangThai CHECK(TrangThai Between 0 and 2),
    CONSTRAINT FK_VatTu_LoaiVT FOREIGN KEY (MaLVT) REFERENCES LoaiVT(MaLVT)
);

-- Tạo bảng GiaoDich
CREATE TABLE GiaoDich (
    MaGD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LoaiGD VARCHAR2(10) NOT NULL,
    ThoiGian DATE DEFAULT SYSDATE,
    ThanhTien NUMBER DEFAULT 0,
    MaNVC NUMBER NOT NULL,
    MaNV NUMBER NOT NULL, --> Xóa ở CT_Nhap và CT_Xuat thêm ở đây
    CONSTRAINT CK_GiaoDich_LoaiGD CHECK (LoaiGD IN ('Nhap', 'Xuat')),
    CONSTRAINT FK_GiaoDich_NhaVanChuyen FOREIGN KEY (MaNVC) REFERENCES NhaVanChuyen(MaNVC)
);

-- Tạo bảng LichSuCapNhat
CREATE TABLE LichSuCapNhat (
    MaLSCN NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaVT NUMBER NOT NULL,
    GiaCu NUMBER,
    GiaMoi NUMBER NOT NULL,
    NgayCapNhat DATE DEFAULT SYSDATE,
    CONSTRAINT FK_LichSuCapNhat_VatTu FOREIGN KEY (MaVT) REFERENCES VatTu(MaVT)
);

-- Tạo bảng CT_Nhap
CREATE TABLE CT_Nhap (
    MaGD NUMBER NOT NULL,
    MaVT NUMBER NOT NULL,
    SL NUMBER NOT NULL,
    ThanhTien NUMBER,
    MaNCC NUMBER NOT NULL,
    CONSTRAINT PK_CT_Nhap PRIMARY KEY (MaGD, MaVT),
    CONSTRAINT FK_CT_Nhap_GiaoDich FOREIGN KEY (MaGD) REFERENCES GiaoDich(MaGD),
    CONSTRAINT FK_CT_Nhap_VatTu FOREIGN KEY (MaVT) REFERENCES VatTu(MaVT),
    CONSTRAINT FK_CT_Nhap_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    CONSTRAINT FK_CT_Nhap_NhaCungCap FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);

-- Tạo bảng CT_Xuat
    CREATE TABLE CT_Xuat (
        MaGD NUMBER NOT NULL,
        MaVT NUMBER NOT NULL,
        SL NUMBER NOT NULL,
        ThanhTien NUMBER,
        MaKH NUMBER NOT NULL,
    CONSTRAINT PK_CT_Xuat PRIMARY KEY (MaGD, MaVT),
    CONSTRAINT FK_CT_Xuat_GiaoDich FOREIGN KEY (MaGD) REFERENCES GiaoDich(MaGD),
    CONSTRAINT FK_CT_Xuat_VatTu FOREIGN KEY (MaVT) REFERENCES VatTu(MaVT),
    CONSTRAINT FK_CT_Xuat_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    CONSTRAINT FK_CT_Xuat_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

-- Tạo bảng LichSuKiemKe
CREATE TABLE LichSuKiemKe (
    MaLSKK NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaNV NUMBER NOT NULL,
    ThoiGian DATE DEFAULT SYSDATE,
    MaVT NUMBER NOT NULL,
    SoLuongConLai NUMBER,
    TinhTrang VARCHAR2(100),
    CONSTRAINT FK_LichSuKiemKe_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
    CONSTRAINT FK_LichSuKiemKe_VatTu FOREIGN KEY (MaVT) REFERENCES VatTu(MaVT)
);


-- Index cho các table

-- KhachHang
CREATE INDEX IDX_KhachHang_SDT ON KhachHang(SDT);

-- NhanVien
CREATE INDEX IDX_NhanVien_ChucVu ON NhanVien(ChucVu);
CREATE INDEX IDX_NhanVien_NgayVaoLam ON NhanVien(NgayVaoLam);

-- NhaVanChuyen
CREATE INDEX IDX_NhaVanChuyen_SDT_DaiDien ON NhaVanChuyen(SDT_DaiDien);

-- VatTu
CREATE INDEX IDX_VatTu_MaLVT ON VatTu(MaLVT);
CREATE INDEX IDX_VatTu_TenVT ON VatTu(TenVT);
CREATE INDEX IDX_VatTu_TrangThai ON VatTu(TrangThai);

-- GiaoDich
CREATE INDEX IDX_GiaoDich_MaNVC ON GiaoDich(MaNVC);
CREATE INDEX IDX_GiaoDich_LoaiGD ON GiaoDich(LoaiGD);
CREATE INDEX IDX_GiaoDich_ThoiGian ON GiaoDich(ThoiGian);

-- LichSuCapNhat
CREATE INDEX IDX_LichSuCapNhat_MaVT ON LichSuCapNhat(MaVT);
CREATE INDEX IDX_LichSuCapNhat_NgayCapNhat ON LichSuCapNhat(NgayCapNhat);

-- CT_Nhap
CREATE INDEX IDX_CT_Nhap_MaGD ON CT_Nhap(MaGD);
CREATE INDEX IDX_CT_Nhap_MaVT ON CT_Nhap(MaVT);
CREATE INDEX IDX_CT_Nhap_MaNV ON CT_Nhap(MaNV);
CREATE INDEX IDX_CT_Nhap_MaNCC ON CT_Nhap(MaNCC);

-- CT_Xuat
CREATE INDEX IDX_CT_Xuat_MaGD ON CT_Xuat(MaGD);
CREATE INDEX IDX_CT_Xuat_MaVT ON CT_Xuat(MaVT);
CREATE INDEX IDX_CT_Xuat_MaNV ON CT_Xuat(MaNV);
CREATE INDEX IDX_CT_Xuat_MaKH ON CT_Xuat(MaKH);

-- LichSuKiemKe
CREATE INDEX IDX_LichSuKiemKe_MaNV ON LichSuKiemKe(MaNV);
CREATE INDEX IDX_LichSuKiemKe_MaVT ON LichSuKiemKe(MaVT);
CREATE INDEX IDX_LichSuKiemKe_ThoiGian ON LichSuKiemKe(ThoiGian);


-- Xóa các bảng có phụ thuộc khóa ngoại trước
--DROP TABLE CT_Xuat CASCADE CONSTRAINTS;
--DROP TABLE CT_Nhap CASCADE CONSTRAINTS;
--DROP TABLE LichSuCapNhat CASCADE CONSTRAINTS;
--DROP TABLE LichSuKiemKe CASCADE CONSTRAINTS;
--DROP TABLE GiaoDich CASCADE CONSTRAINTS;
--DROP TABLE VatTu CASCADE CONSTRAINTS;
--DROP TABLE NhanVien CASCADE CONSTRAINTS;
--DROP TABLE KhachHang CASCADE CONSTRAINTS;
--DROP TABLE NhaCungCap CASCADE CONSTRAINTS;
--DROP TABLE NhaVanChuyen CASCADE CONSTRAINTS;
--DROP TABLE LoaiVT CASCADE CONSTRAINTS;
